export const metadata = {
  title: "My Awesome Site",
  description: "Generated by Next + Sanity",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
