import "./globals.css";
import { Hind_Siliguri } from "next/font/google";
import Footer from "@/app/(project)/components/Footer/Footer";

const font = Hind_Siliguri({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <main>
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
